#!/bin/bash

SCRIP_DIR="$(dirname "$(readlink -f "$0")")"

run_single_test()
{
  echo "Preparing application $1"

  arm-rtems4.11-objcopy -O binary "$1" "$1.bin"
  echo 'end!' >>"$1.bin"

  # 00040040 T _start
  START_ADDRESS="$(arm-rtems4.11-nm "$1" | sed -n -e 's/^\([0-9A-Fa-f]\+\)[ \t]\+T[ \t]\+_start$/\1/p')"

  # 0 .start        000001fc  00040000  00040000  000000c0  2**2
  IMAGE_BASE="$(arm-rtems4.11-objdump --headers "$1" | sed -n -e 's/^ *[0-9]\+[ \t]\+\.start[ \t]\+[0-9A-Fa-f]\+[ \t]\+\([0-9A-Fa-f]\+\)[ \t]\+.*$/\1/p')"

  if [ -z "$IMAGE_BASE" ] ; then
    IMAGE_BASE="$(arm-rtems4.11-objdump --headers "$1" | sed -n -e 's/^ *[0-9]\+[ \t]\+\.text[ \t]\+[0-9A-Fa-f]\+[ \t]\+\([0-9A-Fa-f]\+\)[ \t]\+.*$/\1/p')"
  fi

  if [ -z "$IMAGE_BASE" ] ; then
    echo "Cannot find image base address"
    exit 1
  fi

  #load_image /home/pi/repo/rtems/tms570/bin/ticker.exe.bin 0x80000000 bin
  openocd -f $SCRIP_DIR/openocd.cfg -c "load_image "$1.bin" 0x$IMAGE_BASE bin" -c "resume 0x$START_ADDRESS" &
  OPENOCD_PID=$!
  nc -w 10 -z localhost 4444
  if [ $? -ne 0 ]; then
    echo "OpenOCD start failed"
  fi

  sleep 4

  echo "Running application $1"
  read -p "Inform if test result id OK [y/n]" -t 300 RESPONSE
  if [ $? -ne 0 ]; then
    RESPONSE='Timeout'
  fi

  echo "Test result $RESPONSE" >>"$1.res"

  kill $OPENOCD_PID

  if [ "$RESPONSE" = "q" ] ; then
    echo "Quitting on user resquest"
    exit 1
  fi
}

if [ $# -lt 1 ] ; then
  echo >2 'test.exe is expected as an argument or all to find all *.exe found'
fi

if [ "$1" != "all" ] ; then
  run_single_test "$1"
else
  for e in $(find -name '*.exe' | sort ) ; do
    run_single_test "$e" ;
  done
fi
